config/routes.rb
# -*- encoding : utf-8 -*-
ProfCareer::Application.routes.draw do
  

  mount_sextant if Rails.env.development?

  #mount ImperaviRails::Engine => "/imperavi"

  mount Ckeditor::Engine => '/ckeditor'

  get "admin/login" => "admin#login"
  get "admin_users/sign_in" => "admin#login"
  get "admin/reset_password" => "admin#reset_password"
  post "admin/reset_password_save" => "admin#reset_password_save"
  
  devise_for :admin_users

  root :to => 'home#index'

  namespace :auth do
    post '/login'
    get '/logout'
    get '/register'
    post '/process_registration'
    get '/profile'
    put '/update_profile'
  end

  namespace :remote do
    get '/'=>:index
    namespace :auth do
      get '/register'
      post '/process_registration'
      get '/user_generation'
      post '/login'
      get :profile
      put :update_profile
    end
  end

  namespace :ajax do
    get '/cities'
  end

  namespace :quiz do
    root :to=>:index
    get '/instruction/:id' => :instruction, :as => :instruction
    get '/clear_result/:id' => :clear_result, :as => :clear_result
    get '/result/:id' => :result, :as => :result
    get '/run/:id' => :run, :as => :run
    get '/complete/:id' => :complete, :as => :complete
    match '/answer/:id/:question_id' => :answer, :as => :answer
    match '/view_report'
    match '/download_report'
  end

  get "/admin" => "admin#index", :as=>:admin
  get "/admin/login" => "admin#login", :as => :admin_login
  match '/admin/questions/:action/:id' => 'questions#index'
  match '/admin/questions/:action/:id.:format' => 'questions#index'

  namespace :admin do

# leave that *** after back end changes
    resources :users do
      member do
        get :profile
      end
    end
    resources :projects do
      member do
        get :codes
        get :settings
        get :quizes
        get :move_users
        post :apply_move_users
        get :notice_history
        get :send_all
        get :send_choosed
        get :send_uncompleted
        post :process_send
        get :excel_export
        get :reports
      end
      resources :notices do
        member do
          get :prev
          get :copy
          get :message_text
        end
        collection do
          get :preview
        end
      end
      resources :users do
        collection do
          post :import
          get :import_dialog
        end
        member do
          get :move_to_project
        end        
        resources :quizzes do
          member do
            get :reset
            get :show_answers
            get :show_statistics
            get :export_answers
            get :show_report
            get :export_report
          end
        end  
      end
      resources :quiz do        
      end
      collection do
        get :all_users
        get :users
      end
    end 

    resources :quizzes do
      resources :profile_charachteristic do        
      end
      resources :factors do
      end
      resources :reports do
      end
      member do
        get :settings
        get :statistics
        get :set_period
        get :excel_export
        get :excel_reports
      end
      resources :questions do        
        collection do
          post :save_weights
          post :save_buffering
          post :remove          
        end
        member do
          get :buffering
          get :move
        end
      end
    end

    resources :settings
    resources :pages

    namespace :users do
      match "/"=>:index
      match '/new'
      match '/edit/:id'=>:edit
      match '/update/:id'=>:update
      match '/delete/:id'=>:destroy
      match "/list"
    end

    namespace :quiz do
      match '/'=>:index
      match '/new'
      match '/delete/:id'=>:destroy
      match '/edit/:id'=>:edit
      match '/update/:id'=>:update
      match '/list'
      match '/import'
    end

    namespace :factor do
      match '/new/:id'=>:new
      match '/update/:id'=>:update
      match '/edit/:id'=>:edit
      match '/reorder'
      match '/questions/:id'=>:questions
      match '/delete/:id'=>:destroy
      match '/correlation/:id'=>:correlation
    end

    namespace :report do
      match '/new/:id'=>:new
      match '/update/:id'=>:update
      match '/edit/:id'=>:edit
      match '/delete/:id'=>:destroy
    end

    namespace :interpretation do
      match '/new'
      match '/update/:id'=>:update
      match '/delete/:id'=>:destroy
    end

    namespace :statistics do
      match '/' => :index
      match '/view_report'
      match '/answers'
      match '/user'
      match '/answers'
      match '/export'
      match '/clear_statistic'
    end

    namespace :notice do
      match '/edit'
      match '/create_or_update'
      match '/process_window'
      match '/delete/:id'=>:destroy
      match '/notice_window_content'
    end

    # namespace :pages do
    #   match '/' => :index
    #   match '/new'
    #   match '/edit/:id'=>:edit
    #   match '/update/:id'=>:update
    #   match '/delete/:id'=>:delete
    #   match '/reorder'
    # end

    namespace :properties do
      match '/' => :index
      match '/add' => :add, :as => :add
      match '/view'
      match '/edit/:id'=>:edit, :as => :edit
      match '/update/:id'=>:update, :as => :update
      match '/delete/:id' => :delete, :as => :delete
      match '/reorder/' => :reorder, :as => :reorder
      match '/cities/' => :cities, :as => :cities
      match '/reorder'
      match '/load' => :load, as: :load
      match '/ajax_list_properties/:id'=>:ajax_list_properties
    end

    # namespace :settings do
    #   match '/'=>:index
    #   match '/edit/:id'=>:edit
    #   match '/update/:id'=>:update
    # end

    namespace :userquiz do
      match '/list_json'
      match '/excel_export'
    end
  end

end

app/models/project.rb
# -*- encoding : utf-8 -*-
class Project < ActiveRecord::Base
  has_many :users, :order => 'surname', :dependent=>:destroy
  has_many :notices
  has_many :project_quizzes, :dependent=>:destroy
  has_many :quizzes, :through=>:project_quizzes
  has_many :user_quizzes, :through=>:users
  has_many :sended_notices

  validates :title, :presence => {:message => "Заголовок опроса не может быть пустым"}

  before_destroy{|project| false if project.default?}

  accepts_nested_attributes_for :project_quizzes, :allow_destroy => true

  def to_s
    title
  end

  def show_report_for(quiz)
    project_quizzes.find_by_quiz_id(quiz.id).try(:show_report)
  end

  def find_report(quiz)
  	project_quizzes.find_by_quiz_id(quiz.id).try(:report)
  end

  def user_quizzes_by(quiz)
    user_quizzes.where(:quiz_id=>quiz)
  end

  def statistic
    people_count = users.size
    quizzes.map{|quiz| {:title=>quiz.title, :all=>user_quizzes_by(quiz).size,
      :completed=>user_quizzes_by(quiz).completed.size, :people => people_count}}
  end

  def self.default
    find_by_default(true)
  end

end

# == Schema Information
#
# Table name: projects
#
#  id           :integer(4)      not null, primary key
#  title        :string(255)     not null
#  created_at   :datetime
#  updated_at   :datetime
#  allow_anonim :boolean(1)
#  default      :boolean(1)      default(FALSE)
#  style        :text
#

app/controllers/admin/projects_controller.rb
# -*- encoding : utf-8 -*-
#encoding: utf-8
class Admin::ProjectsController < AdminController

  respond_to :html, :js

  before_filter :init, :except => [ :index, :new, :create, :users, :all_users ]
  before_filter :get_projects, :only => [:index, :show, :users, :all_users, :notice_history]
  before_filter :set_section

  def index
    
  end

  def reports
    render :action => "leave", :layout => false
  end

  def show
    @users = @project.users
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def create
    @project = Project.create(params[:project])    
    @project.save if @project.valid?
    respond_with(@project)
  end

  def edit
    
  end

  def update
    # binding.pry
    @project.update_attributes(params[:project])
    respond_with(@project)
  end

  def destroy
    
  end

  def codes
    respond_with(@project)
  end

  def settings
    respond_with(@project)
  end

  def quizes
    respond_with(@project)
  end

  def all_users
    @active = 1
    @users = User.all
    @project = Project.default
    @all_users = true
    render "admin/users/index"
  end

  def users
    @active = 1
    render "admin/users/index"
  end
  
  def move_users
    @ids = params[:choosed]
    respond_with(@ids)    
  end

  def apply_move_users
    # binding.pry
    @new_proj = Project.find(params[:user][:project_id])
    @users = User.where(id: params[:user][:usr].map { |u| u[0].to_i })
    @users.update_all(project_id: @new_proj.id)
    respond_with(@users)
  end  

  def notice_history
    @project = Project.find(params[:id])
    @notices = @project.sended_notices.order("created_at desc")

    respond_with(@notices)
  end

  def send_all
    @users = @project.users
    @templates = @project.notices
    render :send_notice
  end

  def send_choosed
    # binding.pry
    @users = []
    @choosed = params[:choosed]
    @users = @choosed.collect { |c| User.find(c) } unless @choosed.nil?
    @templates = @project.notices
    render :send_notice
  end

  def send_uncompleted
    @users = @project.user_quizzes.uncompleted.collect { |uq| uq.user }
    @templates = @project.notices
    render :send_notice
  end

  def process_send
    # binding.pry
    @send = params[:send]
    template = Notice.find(@send[:template])
    user_ids = @send[:users]
    t = NoticeRenderer::Template.new
    t.template = template.content
    admin_email = Settings.get(:email)
    other_emails = @send[:admin_email].split(',')
    User.find(user_ids).each do |user|
      t.set_user(user)
      content = t.render()
      Notifier.invite(user, template.theme, content, template, @project).deliver
      Notifier.invite_copy_admin(admin_email, template.theme, content).deliver if @send[:send_copy] == "1"
      other_emails.each { |ae| Notifier.invite_copy_admin(ae, template.theme, content).deliver }
      # SendedNotice.create(user: user, project: @project, notice: template, text: "mail.body")
    end
    respond_with(@project)
  end

  def excel_export
    if params[:choosed].present?
      @users = @project.users.joins(:user_quizzes).where("user_quizzes.user_id in (?)", params[:choosed]).uniq
      @quizzes = @project.quizzes
    else
      @users = @project.users.joins(:user_quizzes).where("user_quizzes.complete = 1").uniq
      @quizzes = @project.quizzes.includes(:completed_users)
    end
    # binding.pry

    headers['Content-Type'] = "application/vnd.ms-excel"                                                                       
    headers['Content-Disposition'] = 'attachment; filename="users_'+ Time.now.strftime("%Y_%D_%H_%M") + '.xls"'                                                      
    headers['Cache-Control'] = ''
    
    render :layout =>false
  end

private 
  def init
    @project = Project.find(params[:id])
  end

  def get_projects
    @projects = Project.all
  end

  def set_section
    @section = "projects"
    @active = 2
  end

end

app/views/shared/projects/_add_dialog.html.haml
:javascript
	$(document).ready(function(){
		$("#add-project-dlg").modal({
			show: true
		});
	});
.modal.hide.fade#add-project-dlg
	.modal-header
		%button.close{ :type => "button", "data-dismiss" => "modal" }= "×"
		%h3= "Новый проект"
	= form_for @project, :url => admin_projects_path, remote: true do |f|
		.modal-body		
			.row
				.span2= f.label :title, "Название"
				.span4= f.text_field :title, :class => "input-xlarge span4"
		.modal-footer
			%a.btn{ :href => "#", "data-dismiss" => "modal" }= "Отмена"			
			%button.btn.btn-primary#add-project-btn{ :type => "submit" }= "Сохранить"

app/views/shared/projects/_answers_dialog.html.haml
:javascript
	$(document).ready(function(){
		$("#answers-dlg").modal({
			show: true
		});
	});
.modal.hide.fade#answers-dlg
	.modal-header
		%button.close{ :type => "button", "data-dismiss" => "modal" }= "×"
		%h3= "Ответы"	
	.modal-body		
		%table.table.table-striped.table-bordered.table-condensed.tablesorter
			%thead
				%tr
					%th= "Вопрос"
					%th= "Ответ"
					%th= "Балл"
			%tbody
				- @quiz.answerable_questions.each  do |q|
					- answer = q.answer_for(@user)
					%tr
						%td= "#{q.number + 1}. #{q.instruction}"
						/ - binding.pry
						- unless answer.blank?
							- begin
								/ %td= q.value_title(answer.raw).force_encoding("utf-8")
								%td= answer.view
							- rescue
								/ - binding.pry
								%td= "n/a"								
							%td= answer.value
						- else
							%td= "N/A"
	.modal-footer
		%a.btn{ :href => "#", "data-dismiss" => "modal" }= "Закрыть"		

app/views/shared/projects/_move_to_project_dialog.html.haml
:javascript
	$(document).ready(function(){
		$("#move-to-project").modal({
			show: true
		});
	});
.modal.hide.fade#move-to-project
	.modal-header
		%button.close{ :type => "button", "data-dismiss" => "modal" }= "×"
		%h3= "Переместить в проект"
	= form_for :user, :url => apply_move_users_admin_project_path(@project), :class => "form-horizontal", :remote => true do |f|
		- @ids.each do |id|
			= f.hidden_field "usr[#{id}]", value: id
		.modal-body		
			.row
				.span2= f.label :project_id, "Выберите проект:"
				.span4= f.collection_select :project_id, Project.all, :id, :title, { :include_blank => false }, :class => "input-xlarge span4"
		.modal-footer
			%a.btn{ :href => "#", "data-dismiss" => "modal" }= "Отмена"
			%button.btn.btn-primary#apply-move-btn{ :type => "submit" }= "Переместить"

app/views/shared/projects/_notice_history_dialog.html.haml
:javascript
	$(document).ready(function(){
		$("#notice-history-dlg").modal({
			show: true
		});
		var tableObj = $('#notice-list').dataTable({
			"sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
			"sPaginationType": "bootstrap",
			"oLanguage": {
				"sProcessing":   "Подождите...",
				"sLengthMenu":   "Показать _MENU_ записей",
				"sZeroRecords":  "Записи отсутствуют.",
				"sInfo":         "Записи с _START_ до _END_ из _TOTAL_",
				"sInfoEmpty":    "Записи с 0 до 0 из 0",
				"sInfoFiltered": "(из _MAX_)",
				"sInfoPostFix":  "",
				"sSearch":       "Поиск:",
				"sUrl":          "",
				"oPaginate": {
					"sFirst": "<<",
					"sPrevious": "<",
					"sNext": ">",
					"sLast": ">>"
				}
			}
		});
	});
.modal.hide.fade#notice-history-dlg
	.modal-header
		%button.close{ :type => "button", "data-dismiss" => "modal" }= "×"
		%h3= "Отправленные уведомления"	
	.modal-body		
		%table.table.table-striped.table-bordered.table-condensed.tablesorter#notice-list
			%thead
				%tr
					%th Дата
					%th Адресат ФИО
					%th Адресат E-mail
					%th Отправитель E-mail
					%th Шаблон

			%tbody
				- @notices.each do |item|
					%tr
						%td= item.created_at.strftime("%Y-%m-%d %H:%M")	
						%td= item.user.title
						%td= item.user.email
						%td= AppConfig.setting[:mail_robot]

						%td
							= link_to message_text_admin_project_notice_path(@project, item.notice, sended_notice_id: item.id), remote: true,  :"data-original-title" => "Просмотр", rel: :tooltip, id: "preview-link" do
								= item.notice.title

	.modal-footer
		%a.btn{ :href => "#", "data-dismiss" => "modal" }= "Закрыть"

app/views/shared/projects/_quiz_control_group.html.haml
- unless UserQuiz.is_started?(user, quiz)
  %div{ style: "float: left; margin-right: 5px; line-height: 28px;", class: "quiz-date" }= user.created_at.strftime("%d.%m.%Y")
  %button.btn{type: "button", disabled: "disabled", style: "width: 52px;"}
    %i.icon-plus-sign
- else      
  - if UserQuiz.not_completed?(user, quiz)
    %div{ :style => "float: left; margin-right: 5px; line-height: 28px;", class: "quiz-date" }
      - unless UserQuiz.get(user, quiz).nil?
        = UserQuiz.get(user, quiz).created_at.strftime("%d.%m.%Y")
      - else
        = "null for (#{user.id}, #{quiz.id})"
    .btn-group
      = link_to '#', :class => "btn btn-warning dropdown-toggle", "data-toggle" => "dropdown" do    
        %i.icon-time
        %span.caret
      %ul.dropdown-menu
        %li
          = link_to reset_admin_project_user_quiz_path(user.project, user, quiz), remote: true, confirm: "Вы уверены?" do
            %i.icon-remove
            = "Сбросить"
  - else
    %div{ :style => "float: left; margin-right: 5px; line-height: 28px;", class: "quiz-date" }
      = UserQuiz.get(user, quiz).updated_at.strftime("%d.%m.%Y")
    .btn-group
      = link_to '#', :class => "btn btn-success dropdown-toggle", "data-toggle" => "dropdown" do
        %i.icon-ok-circle        
        %span.caret
      %ul.dropdown-menu
        %li.dropdown-submenu        
          = link_to "Отчет", '#', tabindex: -1
          %ul.dropdown-menu
            %li.view-report
              = link_to show_report_admin_project_user_quiz_path(user.project, user, quiz), remote: true do
                %i.icon-eye-open
                = "Просмотр"
            %li
              = link_to export_report_admin_project_user_quiz_path(user.project, user, quiz, format: :html), target: :blank do
                %i.icon-share
                = "Версия для печати"
            %li
              = link_to export_report_admin_project_user_quiz_path(user.project, user, quiz, format: :pdf), target: :blank do
                %i.icon-share
                = "PDF версия"
            %li
              = link_to export_report_admin_project_user_quiz_path(user.project, user, quiz, anketa: true, format: :pdf), target: :blank do
                %i.icon-share
                = "PDF версия с анкетой"
        %li.divider
        %li.dropdown-submenu        
          = link_to "Ответы", '#', tabindex: -1
          %ul.dropdown-menu
            %li.view-answers
              = link_to show_answers_admin_project_user_quiz_path(user.project, user, quiz), remote: true do
                %i.icon-eye-open
                = "Просмотр"
            %li
              = link_to reset_admin_project_user_quiz_path(user.project, user, quiz), remote: true, confirm: "Вы уверены?" do
                %i.icon-remove
                = "Сбросить"
            %li          
              = link_to export_answers_admin_project_user_quiz_path(user.project, user, quiz, values: false, format: :html), target: :blank do
                %i.icon-share
                = "Версия для печати - только ответы"
            %li
              = link_to export_answers_admin_project_user_quiz_path(user.project, user, quiz, values: true, format: :html), target: :blank do
                %i.icon-share
                = "Версия для печати - ответы и баллы"
            %li
              = link_to export_answers_admin_project_user_quiz_path(user.project, user, quiz, values: false, format: :pdf), target: :blank do
                %i.icon-share
                = "PDF версия - только ответы"
            %li
              = link_to export_answers_admin_project_user_quiz_path(user.project, user, quiz, values: true, format: :pdf), target: :blank do
                %i.icon-share
                = "PDF версия - ответы и баллы"        
        %li.divider
        %li.dropdown-submenu
          = link_to "Статистика", '#', tabindex: -1
          %ul.dropdown-menu
            %li.view-stat
              = link_to show_statistics_admin_project_user_quiz_path(user.project, user, quiz), remote: true do
                %i.icon-eye-open
                = "Просмотр"

app/views/shared/projects/_quizes_dialog.html.haml
:javascript
	$(document).ready(function(){		
		function getReports(element){
		    var quiz_id = $(element).attr("value");
		    var select_id = $(element).attr("data-type");
		    var selected_id = $(element).attr("data-value");
		    
		    var el = $("#r"+select_id);

		    $.get('#{params[:id]}/reports?quiz_id='+quiz_id+'&value='+selected_id, function(data){
		      $(el).empty();
		      $(el).append(data);
		    });
		};

		function getReports_withoudID(element){
			var quiz_id = $(element).attr("value");
			var selected_id = $(element).attr("data-value");

			var el = $(element).parent().next().find('select');

			$.get('#{params[:id]}/reports?quiz_id='+quiz_id+'&value='+selected_id, function(data){
				$(el).empty();
				$(el).append(data);
			});
		};

		$("#project-polls-dlg").modal({
			show: true
		});

		$('.select-quiz').each(function(){
			getReports(this);
		});

		$('.addEl').click(function(){
			var el = $('.select-quiz').last();
			console.log(el.html());
			getReports_withoudID(el);
		});

		RadioButtons = {
			refresh: function(){
				$('div.btn-group[data-toggle-name=*]').each(function(){
					var group   = $(this);
					var form    = group.parents('form').eq(0);
					var name    = group.attr('data-toggle-name');
					var hidden  = $(group).next();
					$('button', group).each(function(){
					  var button = $(this);
					  button.live('click', function(){	      	
					    hidden.val($(this).val());
					  });
					  if(button.val() == hidden.val()) {
					    button.addClass('active');
					  }
					});
				});
			}
		}
		RadioButtons.refresh();
	});

.modal.hide.fade#project-polls-dlg
	.modal-header
		%button.close{ :type => "button", "data-dismiss" => "modal" }= "×"
		%h3= "Опросы проекта"

	= form_for @project, url: admin_project_path(@project), remote: true, :class => "form-horizontal" do |f|
		.modal-body			
			#quiz-container
				= f.fields_for :project_quizzes do |builder|
					= render "admin/projects/project_quiz_fields", f: builder
			= link_to_add_fields "Добавить опрос", f, :project_quizzes, "#quiz-container", "last", {class: "btn addEl"}
		.modal-footer
			%a.btn{ :href => "#", "data-dismiss" => "modal" }= "Закрыть"
			%button.btn.btn-primary#save-project-btn{ :type => "submit" }= "Сохранить"

app/views/shared/projects/_send_notice_dialog.html.haml
:javascript
	$(document).ready(function(){
		$("#notice-history-dlg").modal({
			show: true
		});

		$('#notice-history-dlg').on('hide', function () {
			$.noty.close(window.previewAlert);
		});

		var tableObj = $('#notice-list').dataTable({
			"sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
			"sPaginationType": "bootstrap",
			"aoColumns":[{ "bSortable": false },null,null],
			"oLanguage": {
				"sProcessing":   "Подождите...",
				"sLengthMenu":   "Показать _MENU_ записей",
				"sZeroRecords":  "Записи отсутствуют.",
				"sInfo":         "Записи с _START_ до _END_ из _TOTAL_",
				"sInfoEmpty":    "Записи с 0 до 0 из 0",
				"sInfoFiltered": "(из _MAX_)",
				"sInfoPostFix":  "",
				"sSearch":       "Поиск:",
				"sUrl":          "",
				"oPaginate": {
					"sFirst": "<<",
					"sPrevious": "<",
					"sNext": ">",
					"sLast": ">>"
				}
			}
		});
		Service.refreshBootstrapRadio();
		$("a[rel='tooltip']").tooltip();
		$("#send_template").change(function(){
			base_url = "#{preview_admin_project_notices_path(@project)}"
			url = base_url + "?template_id=" + $(this).val();
			$("#preview-link").attr('href', url);
			return false;
		});
	});
.modal.hide.fade#notice-history-dlg{ style: "margin-top: 0px !important; top: 0px;" }
	.modal-header
		%button.close{ :type => "button", "data-dismiss" => "modal" }= "×"
		%h3= "Отправить уведомление"	
	= form_for :send, url: process_send_admin_project_path(@project), remote: true do |f|
		.modal-body{style: "max-height: 600px;"}
			%fieldset
				%legend= "Шаблон:"
				.row
					.span4= f.label :template, "Шаблон"
					.span3
						.input-append
							= f.select :template, @templates.collect{|t|[t.title, t.id] } , :include_blank => false
							= link_to preview_admin_project_notices_path(@project, template_id: @templates.count > 0 ? @templates.first.id : ""), remote: true, class: :btn, :"data-original-title" => "Просмотр", rel: :tooltip, id: "preview-link" do
								%i.icon-eye-open
							= link_to new_admin_project_notice_path(@project, section: :projects), remote: true, class: :btn, :"data-original-title" => "Добавить новый", rel: :tooltip do
								%i.icon-plus						
				.row
					.span4= f.label :priority, "Приоритет"
					.span3
						.btn-group#radio{ "data-toggle" => "buttons-radio", :"data-toggle-name" => "send[priority]" }
							%button.btn{ :type => "button", value: 0 }= "Низкий"
							%button.btn{ :type => "button", value: 1 }= "Средний"
							%button.btn{ :type => "button", value: 2 }= "Высокий"
						= f.hidden_field :priority
				.row{ style: "margin-top: 10px;" }
					.span4= f.label :send_copy, "Отправить копию на e-mail админа"
					.span3
						.btn-group#radio{ "data-toggle" => "buttons-radio", :"data-toggle-name" => "send[send_copy]" }
							%button.btn{ :type => "button", value: 1 }= "Да"
							%button.btn{ :type => "button", value: 0 }= "Нет"
						= f.hidden_field :send_copy
				.row{ style: "margin-top: 10px;" }
					.span4= f.label :send_copy_2, "Отправить копию на следующие e-mail"
					.span3= f.text_field :admin_email, value: "", class: :span3
			%fieldset
				%legend= "Кому:"
				%table.table.table-striped.table-bordered.table-condensed#notice-list
					%thead
						%tr
							%th.center
							%th Имя Фамилия									
							%th E-mail						
					%tbody
						- @users.each do |user|
							%tr
								%td.center= check_box_tag "send[users][]", user.id, true
								%td= user.title
								%td= user.email
		.modal-footer
			%a.btn{ :href => "#", "data-dismiss" => "modal" }= "Закрыть"
			%button.btn.btn-primary{ type: :submit }= "Отправить"

app/views/shared/projects/_settings_dialog.html.haml
:javascript
	$(document).ready(function(){		
		$("#project-settings-dlg").modal({
			show: true
		});
		$('div.btn-group[data-toggle-name=*]').each(function(){
			var group   = $(this);
			var form    = group.parents('form').eq(0);
			var name    = group.attr('data-toggle-name');
			var hidden  = $('input[name="' + name + '"]', form);
			$('button', group).each(function(){
			  var button = $(this);
			  button.live('click', function(){	      	
			    hidden.val($(this).val());
			  });
			  if(button.val() == hidden.val()) {
			    button.addClass('active');
			  }
			});
		});
	});
.modal.hide.fade#project-settings-dlg
	.modal-header
		%button.close{ :type => "button", "data-dismiss" => "modal" }= "×"
		%h3= "Параметры проекта"
	= form_for @project, :url => admin_project_path(@project), method: "PUT", remote: true, class: "form-horizontal" do |f|
		.modal-body			
			.row
				.span2= f.label :title, "Заголовок"
				.span5= f.text_field :title, :class => "input-xlarge span5"					
			.row
				.span2= f.label :style, "CSS проекта"
				.span5= f.text_area :style, :class => "input-xlarge span5", :rows => "6"
			.row.mt5
				.span2= f.label :allow_anonim, "Анонимная регистрация?"
				.span2
					.btn-group#radio{ :"data-toggle" => "buttons-radio", :"data-toggle-name" => "project[allow_anonim]" }
						%button.btn{ :type => "button", :value => 1 }= "Да"
						%button.btn{ :type => "button", :value => 0 }= "Нет"
					= f.hidden_field :allow_anonim
			.row.mt5
				.span2= f.label :default, "Проект по-умолчанию?"
				.span2
					.btn-group#radio{ :"data-toggle" => "buttons-radio", :"data-toggle-name" => "project[default]" }
						%button.btn{ :type => "button", :value => 1 }= "Да"
						%button.btn{ :type => "button", :value => 0 }= "Нет"
					= f.hidden_field :default
		.modal-footer
			%a.btn{ :href => "#", "data-dismiss" => "modal" }= "Закрыть"			
			%button.btn.btn-primary#update-project-btn{ :type => "submit" }= "Сохранить"