config/routes.rb
# -*- encoding : utf-8 -*-
ProfCareer::Application.routes.draw do
  

  mount_sextant if Rails.env.development?

  #mount ImperaviRails::Engine => "/imperavi"

  mount Ckeditor::Engine => '/ckeditor'

  get "admin/login" => "admin#login"
  get "admin_users/sign_in" => "admin#login"
  get "admin/reset_password" => "admin#reset_password"
  post "admin/reset_password_save" => "admin#reset_password_save"
  
  devise_for :admin_users

  root :to => 'home#index'

  namespace :auth do
    post '/login'
    get '/logout'
    get '/register'
    post '/process_registration'
    get '/profile'
    put '/update_profile'
  end

  namespace :remote do
    get '/'=>:index
    namespace :auth do
      get '/register'
      post '/process_registration'
      get '/user_generation'
      post '/login'
      get :profile
      put :update_profile
    end
  end

  namespace :ajax do
    get '/cities'
  end

  namespace :quiz do
    root :to=>:index
    get '/instruction/:id' => :instruction, :as => :instruction
    get '/clear_result/:id' => :clear_result, :as => :clear_result
    get '/result/:id' => :result, :as => :result
    get '/run/:id' => :run, :as => :run
    get '/complete/:id' => :complete, :as => :complete
    match '/answer/:id/:question_id' => :answer, :as => :answer
    match '/view_report'
    match '/download_report'
  end

  get "/admin" => "admin#index", :as=>:admin
  get "/admin/login" => "admin#login", :as => :admin_login
  match '/admin/questions/:action/:id' => 'questions#index'
  match '/admin/questions/:action/:id.:format' => 'questions#index'

  namespace :admin do

# leave that *** after back end changes
    resources :users do
      member do
        get :profile
      end
    end
    resources :projects do
      member do
        get :codes
        get :settings
        get :quizes
        get :move_users
        post :apply_move_users
        get :notice_history
        get :send_all
        get :send_choosed
        get :send_uncompleted
        post :process_send
        get :excel_export
        get :reports
      end
      resources :notices do
        member do
          get :prev
          get :copy
          get :message_text
        end
        collection do
          get :preview
        end
      end
      resources :users do
        collection do
          post :import
          get :import_dialog
        end
        member do
          get :move_to_project
        end        
        resources :quizzes do
          member do
            get :reset
            get :show_answers
            get :show_statistics
            get :export_answers
            get :show_report
            get :export_report
          end
        end  
      end
      resources :quiz do        
      end
      collection do
        get :all_users
        get :users
      end
    end 

    resources :quizzes do
      resources :profile_charachteristic do        
      end
      resources :factors do
      end
      resources :reports do
      end
      member do
        get :settings
        get :statistics
        get :set_period
        get :excel_export
        get :excel_reports
      end
      resources :questions do        
        collection do
          post :save_weights
          post :save_buffering
          post :remove          
        end
        member do
          get :buffering
          get :move
        end
      end
    end

    resources :settings
    resources :pages

    namespace :users do
      match "/"=>:index
      match '/new'
      match '/edit/:id'=>:edit
      match '/update/:id'=>:update
      match '/delete/:id'=>:destroy
      match "/list"
    end

    namespace :quiz do
      match '/'=>:index
      match '/new'
      match '/delete/:id'=>:destroy
      match '/edit/:id'=>:edit
      match '/update/:id'=>:update
      match '/list'
      match '/import'
    end

    namespace :factor do
      match '/new/:id'=>:new
      match '/update/:id'=>:update
      match '/edit/:id'=>:edit
      match '/reorder'
      match '/questions/:id'=>:questions
      match '/delete/:id'=>:destroy
      match '/correlation/:id'=>:correlation
    end

    namespace :report do
      match '/new/:id'=>:new
      match '/update/:id'=>:update
      match '/edit/:id'=>:edit
      match '/delete/:id'=>:destroy
    end

    namespace :interpretation do
      match '/new'
      match '/update/:id'=>:update
      match '/delete/:id'=>:destroy
    end

    namespace :statistics do
      match '/' => :index
      match '/view_report'
      match '/answers'
      match '/user'
      match '/answers'
      match '/export'
      match '/clear_statistic'
    end

    namespace :notice do
      match '/edit'
      match '/create_or_update'
      match '/process_window'
      match '/delete/:id'=>:destroy
      match '/notice_window_content'
    end

    # namespace :pages do
    #   match '/' => :index
    #   match '/new'
    #   match '/edit/:id'=>:edit
    #   match '/update/:id'=>:update
    #   match '/delete/:id'=>:delete
    #   match '/reorder'
    # end

    namespace :properties do
      match '/' => :index
      match '/add' => :add, :as => :add
      match '/view'
      match '/edit/:id'=>:edit, :as => :edit
      match '/update/:id'=>:update, :as => :update
      match '/delete/:id' => :delete, :as => :delete
      match '/reorder/' => :reorder, :as => :reorder
      match '/cities/' => :cities, :as => :cities
      match '/reorder'
      match '/load' => :load, as: :load
      match '/ajax_list_properties/:id'=>:ajax_list_properties
    end

    # namespace :settings do
    #   match '/'=>:index
    #   match '/edit/:id'=>:edit
    #   match '/update/:id'=>:update
    # end

    namespace :userquiz do
      match '/list_json'
      match '/excel_export'
    end
  end

end

app/controllers/admin/quizzes_controller.rb
# -*- encoding : utf-8 -*-
#encoding: utf-8
class Admin::QuizzesController < AdminController
  include Admin::QuizHelper

  layout 'admin_bootstrap', except: [:export_answers, :export_report]
  
  respond_to :html, :js, :pdf

  before_filter :get_quizzes
  before_filter :find_user, only: [:reset, :show_answers, :show_statistics, :export_answers, :show_report, :export_report]
  before_filter :find_quiz, only: [:set_period, :show, :edit, :update, :settings, :destroy, :statistics, :reset, :show_answers, 
    :show_statistics, :export_answers, :show_report, :export_report, :excel_export, :excel_reports]

  def index
  end

  def show
  end

  def new
  	@quiz = Quiz.new
  	respond_with(@quiz)
  end

  def create
  	@quiz = Quiz.new(params[:quiz])
    # binding.pry
  	@quiz.save if @quiz.valid?
  	respond_with(@quiz)
  end

  def edit
  end

  def update
    # binding.pry
    @quiz.update_attributes(params[:quiz])
    respond_with(@quiz)
  end

  def destroy
    @quiz.destroy
    flash[:notice] = "Опрос успешно удален!"
    redirect_to admin_quizzes_path
  end

  def settings
  end

  def statistics
    # binding.pry
    @min_date = @quiz.user_quizzes.order('updated_at').first
    @questions = @quiz.questions
  end

  def reset    
    uq = UserQuiz.get(@user, @quiz)
    uq.destroy
    respond_with(@user)
  end

  def show_answers
    @project = Project.find(params[:project_id])
    @user_quiz = UserQuiz.get(@user, @quiz)
    respond_with(@user_quiz)
  end

  def export_answers
    @project = Project.find(params[:project_id])
    @user_quiz = UserQuiz.get(@user, @quiz)
    respond_with(@user_quiz, layout: false)
  end

  def show_statistics
    @project = Project.find(params[:project_id])
    respond_with(@quiz)
  end

  def show_report
    @project = Project.find(params[:project_id])
    @user_quiz = UserQuiz.get(@user, @quiz)
    respond_with(@user_quiz)
  end

  def export_report
    @project = Project.find(params[:project_id])
    @user_quiz = UserQuiz.get(@user, @quiz)
    respond_with(@user_quiz, layout: false)
  end

  def set_period    
    
    if @first_date = params[:param][:start_date] 
      @first_date = params[:param][:start_date].to_date
      deleted_answers = []
      if @quiz.user_quizzes.only_deleted.where("created_at > ?", @first_date).count > 0 
      
        @quiz.user_quizzes.only_deleted.where("created_at > ?", @first_date).includes(:user).each do |user_quiz|
          user_quiz.user.answers.only_deleted.each do |answer|
            if answer.updated_at > @first_date 
              deleted_answers << answer.id
            end
          end 
          Answer.only_deleted.where('id in (?)', deleted_answers).each {|ans| ans.add_hit(nil)}
          user_quiz.add_hit(nil)      
        end
        
      end
      answers = []
      # binding.pry
      @quiz.user_quizzes.completed.where("created_at < ?", @first_date).includes(:user).each do |user_quiz|
        unless user_quiz.user.nil?
          user_quiz.user.answers.each do |answer|
            if answer.updated_at < @first_date 
              answers << answer.id
            end
          end
        end
        Answer.where('id in (?)', answers).each {|ans| ans.add_hit(Time.now)}
        user_quiz.add_hit(Time.now)
      end 
      @quiz.elaborate_statistics
      redirect_to :back 
    end
  end

  def excel_export
    statistic = Statistic.create content_id: @quiz.id
    Delayed::Job.enqueue(ExportQuizzesJob.new @quiz.id, statistic.id)
    redirect_to excel_reports_admin_quiz_path(@quiz), notice: I18n.t('reports.success')
    # render layout: false
  end

  def excel_reports
    @xlss = Statistic.where(content_id: @quiz.id)
    respond_with(@xlss)
  end

  private

  def get_quizzes
  	@quizzes = Quiz.all
    @active = 4
  end

  def find_quiz
  	@quiz = Quiz.find(params[:id])
  end

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/views/admin/quizzes/_main_part.html.haml
:javascript
	$(document).ready(function(){
		api = $("#question-editor").data('api');
		api.savePositionsUrl = "#{save_weights_admin_quiz_questions_path(@quiz)}";
		api.saveBufferingUrl = "#{save_buffering_admin_quiz_questions_path(@quiz)}";
		api.removeGroupUrl = "#{remove_admin_quiz_questions_path(@quiz)}";
		api.refreshQuestionNumbers();
	});

.center-pane.quiz#question-editor
	.tab-pane.active#tab_answers_editor
		/ .add-panel
		/ 	.row
		/ 		.span2 Добавить элемент:
		/ 	.row
		/ 		.span7
		/ 			.btn-group
		/ 				= link_to "Разделитель", admin_quiz_questions_path(@quiz, type: "divider"), method: :post, remote: true, class: "btn"
		/ 				= link_to "Инструкция", admin_quiz_questions_path(@quiz, type: "instruction"), method: :post, remote: true, class: "btn"
		/ 	.row
		/ 		.span2 Добавить вопрос:
		/ 	.row
		/ 		.span7
		/ 			.btn-group
		/ 				- if @quiz.kind != 'belbin'
		/ 					= link_to "Выбор варианта", admin_quiz_questions_path(@quiz, type: "variant"), method: :post, remote: true, class: "btn"
		/ 					= link_to "Шкала", admin_quiz_questions_path(@quiz, type: "scale"), method: :post, remote: true, class: "btn"						
		/ 					= link_to "Открытый", admin_quiz_questions_path(@quiz, type: "open"), method: :post, remote: true, class: "btn"
		/ 					= link_to "Ранжированый", admin_quiz_questions_path(@quiz, type: "range"), method: :post, remote: true, class: "btn" 
		/ 				= link_to "Ранг=Фактор", admin_quiz_questions_path(@quiz, type: "belbin_range"), method: :post, remote: true, class: "btn" if @quiz.belbin?
						
		%ul#quiz-source.connectedSortable
			- @quiz.answerable_questions.unbuffered.each do |question|
				= render "shared/quizzes/questions/view/#{question.path}", question: question

app/views/admin/quizzes/_quiz_page.html.haml
= javascript_include_tag 'jquery.metadata', 'jquery.scrollIntoView', 'jquery.viewport'
= javascript_include_tag 'admin/quizzes'

#quiz-dialog-container

.left-pane.projects	
	= link_to "Добавить опрос", new_admin_quiz_path, class: "btn btn-success btn-large", remote: true
	.well
		%ul.nav.nav-list#quiz-list
			%li.nav-header Опросы
			- @quizzes.each do |quiz|
				%li{ :class => !@quiz.nil? && @quiz.id == quiz.id ? "active" : "" }
					= link_to admin_quiz_path(quiz) do
						%i.icon-list-alt
						= quiz.title

- unless @quiz.nil?
	= render "main_part"
	= render "right_part", active: :quiz

app/views/admin/quizzes/_right_part.html.haml
- active ||= ""

.right-pane.actions#quiz-buffer-wrapper
	.well
		%ul.nav.nav-list
			%li.nav-header.expanded{ data: { toggle: "add-element" } } Добавить элемент
			%li{ data: {element: 'add-element'} }
				= link_to admin_quiz_questions_path(@quiz, type: "divider"), method: :post, remote: true do
					%i.icon-minus
					Разделитель
			%li{ data: {element: 'add-element'} }
				= link_to admin_quiz_questions_path(@quiz, type: "instruction"), method: :post, remote: true do
					%i.icon-comment
					Инструкция

			%li.nav-header.expanded{ data: { toggle: "add-question" } } Добавить вопрос
			- if @quiz.kind != 'belbin'
				%li{ data: {element: 'add-question'} }
					= link_to admin_quiz_questions_path(@quiz, type: "variant"), method: :post, remote: true do
						%i.icon-list
						Выбор варианта
				%li{ data: {element: 'add-question'} }
					= link_to admin_quiz_questions_path(@quiz, type: "scale"), method: :post, remote: true do
						%i.icon-tasks
						Шкала
				%li{ data: {element: 'add-question'} }
					= link_to admin_quiz_questions_path(@quiz, type: "open"), method: :post, remote: true do
						%i.icon-question-sign
						Открытый
				%li{ data: {element: 'add-question'} }
					= link_to admin_quiz_questions_path(@quiz, type: "range"), method: :post, remote: true do
						%i.icon-random
						Ранжированый
			- else
				%li{ data: {element: 'add-question'} }
					= link_to admin_quiz_questions_path(@quiz, type: "belbin_range"), method: :post, remote: true do
						%i.icon-plus
						Ранг=Фактор

		%ul.nav.nav-list
			%li.nav-header.expanded{ data: { toggle: "quiz" } } Опрос
			%li{ data: { element: :quiz } }
				= link_to excel_export_admin_quiz_path(@quiz) do
					%i.icon-share
					Экспорт в Excel
			%li{ :class => active.to_s == "excel_reports" ? "active" : "", data: {element: 'quiz'} }
				= link_to excel_reports_admin_quiz_path(@quiz) do
					%i.icon-download-alt
					Подготовленные отчеты
			%li{ :class => active.to_s == "quiz" ? "active" : "", data: {element: 'quiz'} }
				= link_to admin_quiz_path(@quiz) do
					%i.icon-th-list
					Редактор вопросов
			%li{ :class => active.to_s == "settings" ? "active" : "", data: {element: 'quiz'} }
				= link_to settings_admin_quiz_path(@quiz) do
					%i.icon-cog
					Параметры
			%li{ :class => active.to_s == "statistics" ? "active" : "", data: {element: 'quiz'} }
				= link_to statistics_admin_quiz_path(@quiz) do
					%i.icon-signal
					Статистика по ответам
			%li{ :class => active.to_s == "factors" ? "active" : "", data: {element: 'quiz'} }
				= link_to admin_quiz_factors_path(@quiz) do
					%i.icon-screenshot
					Факторы
			%li{ :class => active.to_s == "reports" ? "active" : "", data: {element: 'quiz'} }
				= link_to admin_quiz_reports_path(@quiz) do
					%i.icon-file
					Типы отчетов
			%li{ :class => active.to_s == "profiles" ? "active" : "", data: {element: 'quiz'} }
				= link_to admin_quiz_profile_charachteristic_index_path(@quiz) do
					%i.icon-asterisk
					Характеристики профиля
			- if active.to_s == "quiz"
				%li.nav-header.expanded{ data: { toggle: "operations" } } Операции
				%li#remove-selected{ data: {element: 'operations'} }
					= link_to "#" do
						%i.icon-remove-circle
						Удалить
				%li#buffered-selected{ data: {element: 'operations'} }
					= link_to "#" do
						%i.icon-share-alt
						Переместить в буфер
				%li#source-unselect-all{ data: {element: 'operations'} }
					= link_to "#" do
						%i.icon-minus
						Снять выделение
				%li.nav-header.expanded{ data: { toggle: "buffer" } } Буфер
				%li#buffer-select-all{ data: {element: 'buffer'} }
					= link_to "#" do
						%i.icon-ok-circle
						Выделить все
				%li#buffer-unselect-all{ data: {element: 'buffer'} }
					= link_to "#" do
						%i.icon-remove-circle
						Снять все
		- if active.to_s == "quiz"
			%ul#quiz-buffer.connectedSortable.empty{ data: {element: 'buffer'} }
				%li.empty
					%i.icon-copy-paste
					Переместить вопросы в буфер обмена			
				- @quiz.answerable_questions.buffered.each do |question|
					= render "shared/quizzes/questions/view/#{question.path}", question: question

app/views/admin/quizzes/_statistic_table.html.haml
%table.table.table-striped.table-bordered.table-condensed.tablesorter
	%thead
		%tr
			%td Вопрос
			%td Значительно снизит мое желание работать
			%td Снизит мое желание работать
			%td Никак не повлияет на мое желание работать
			%td Повысит мое желание работать
			%td Значительно повысит мое желание работать
			%td Всего ответов
	%tbody

app/views/admin/quizzes/create.js.erb
<% if @quiz.valid? %>
	window.location.href = "<%= admin_quiz_url(@quiz) %>";
<% else %>
	Service.showNoty('Не все поля заполнены!', 'error');
<% end %>

app/views/admin/quizzes/excel_reports.html.haml
:javascript
	$(document).ready(function(){
	  var cols = [null,null,null];
	  var tableObj = $('#reports-list').dataTable({
	    "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
	    "sPaginationType": "bootstrap",
	    "aoColumns": cols,
	    "aaSorting": [[0, "desc"]],
	    "oLanguage": {
	      "sProcessing":   "Подождите...",
	      "sLengthMenu":   "Показать _MENU_ записей",
	      "sZeroRecords":  "Записи отсутствуют.",
	      "sInfo":         "Записи с _START_ до _END_ из _TOTAL_",
	      "sInfoEmpty":    "Записи с 0 до 0 из 0",
	      "sInfoFiltered": "(отфильтровано из _MAX_ записей)",
	      "sInfoPostFix":  "",
	      "sSearch":       "Поиск:",
	      "sUrl":          "",
	      "oPaginate": {
	          "sFirst": "<<",
	          "sPrevious": "Пред.",
	          "sNext": "След.",
	          "sLast": ">>"
	      }
	    }
	  });
	});

#quiz-dialog-container

.left-pane.projects	
	= link_to "Добавить опрос", new_admin_quiz_path, class: "btn btn-success btn-large", remote: true
	.well
		%ul.nav.nav-list#quiz-list
			%li.nav-header Опросы
			- @quizzes.each do |quiz|
				%li{ :class => !@quiz.nil? && @quiz.id == quiz.id ? "active" : "" }
					= link_to excel_reports_admin_quiz_path(quiz) do
						%i.icon-list-alt
						= quiz.title

.center-pane.quiz
	.dash-table
		.title
			Подготовленные отчеты (Excel)
			%span= "[#{@quiz.title}]"

	- unless flash[:notice].nil?
		.alert.alert-success= flash[:notice]

	%table.table.table-bordered.table-condensed.tablesorter#reports-list
		%thead
			%th Дата запроса
			%th Дата создания
			%th Ссылка
		%tbody
			- @xlss.each do |xls|
				%tr{class: xls.path.nil? ? 'success' : '' }
					%td= xls.created_at
					%td
						= xls.path.nil? ? 'Не создано' : xls.updated_at
					%td
						- unless xls.path.nil?
							= link_to "#{xls.path}" do
								%code= xls.path
						- else
							В обработке



= render "right_part", active: :excel_reports

app/views/admin/quizzes/export_answers.html.haml
%html
  %head
    = stylesheet_link_tag "report", media: :print
    :css
      body { font-family: Verdana, Arial, sans-serif; font-size: 12px; background: white;}
      td.instruction { width: 60%;}
      <% if @values  %>
      td.answer { width: 35%; }
      <% else %>
      td.answer { width: 40%; }
      <% end %>
      td.value  { width: 5%; text-align: center;}
      .statistics-table { border: 1px; border-collapse: collapse;}
      .statistics-table td, .statistics-table th { border: 1px solid #A0A0A0; font-size: 12px; padding: 3px;}
  
  %body
    %button.btn{onClick: "window.print()"} Распечатать
    %h2= "#{@user.surname} #{@user.name}"
    %h2= @quiz.title    
    %table.statistics-table
      %thead
        %tr
          %th= "Вопрос"
          %th= "Ответ"
          - if params[:values] == 'true'
            %th= "Балл"
      %tbody
        - @quiz.answerable_questions.each  do |q|
          - answer = q.answer_for(@user)          
          %tr
            %td.instruction= "#{q.number + 1}. #{q.instruction}"
            - unless answer.blank?
              - begin                
                %td.answer= answer.view
              - rescue                
                %td= "n/a"                
              - if params[:values] == 'true'
                %td.value= answer.value
            - else
              %td= "N/A"

app/views/admin/quizzes/new.js.erb
$("#quiz-dialog-container").html("<%= j(render "shared/quizzes/add_dialog") %>");

app/views/admin/quizzes/reset.js.erb
Service.updateUser("<%= j(render "admin/projects/user_item", user: @user) %>", <%= @user.id %>);
Service.showNoty("Результаты опроса усепешно сброшены!");

app/views/admin/quizzes/settings.html.haml
= javascript_include_tag 'redactor', 'redactor.ru'
= stylesheet_link_tag 'redactor'

#quiz-dialog-container

.left-pane.projects	
	= link_to "Добавить опрос", new_admin_quiz_path, class: "btn btn-success btn-large", remote: true
	.well
		%ul.nav.nav-list#quiz-list
			%li.nav-header Опросы
			- Quiz.all.each do |quiz|
				%li{ :class => !@quiz.nil? && @quiz.id == quiz.id ? "active" : "" }
					= link_to admin_quiz_path(quiz) do
						%i.icon-list-alt
						= quiz.title

= render "shared/quizzes/settings_page"
= render "right_part", active: :settings

app/views/admin/quizzes/show.html.haml
= render 'quiz_page'

app/views/admin/quizzes/show_answers.js.erb
<% if @user_quiz.complete? %>
	$("#users-dialog-container").html("<%= j render "shared/projects/answers_dialog" %>");
<% else %>
	Service.showNoty('Опрос еще не завершен!', 'error');
<% end %>

app/views/admin/quizzes/show_statistics.js.erb
<% if @quiz.test? %>
	$("#users-dialog-container").html("<%= j render "shared/projects/statistics_dialog" %>");
<% else %>
	Service.showNoty('Расчет статистики выполняется только для тестов!', 'error');
<% end %>

app/views/admin/quizzes/update.js.erb
<% if @quiz.valid? %>	
	$("#quiz-dialog-container").html('');
	Service.showNoty("Данные успешно сохранены!");
<% else %>
	<% @quiz.errors.messages.each do |field, message| %>
		<% message.each do |mes| %>
			Service.showNoty("<%= mes %>", 'error', 3000);
		<% end %>
	<% end %>
<% end %>