config/routes.rb
# -*- encoding : utf-8 -*-
ProfCareer::Application.routes.draw do
  

  mount_sextant if Rails.env.development?

  #mount ImperaviRails::Engine => "/imperavi"

  mount Ckeditor::Engine => '/ckeditor'

  get "admin/login" => "admin#login"
  get "admin_users/sign_in" => "admin#login"
  get "admin/reset_password" => "admin#reset_password"
  post "admin/reset_password_save" => "admin#reset_password_save"
  
  devise_for :admin_users

  root :to => 'home#index'

  namespace :auth do
    post '/login'
    get '/logout'
    get '/register'
    post '/process_registration'
    get '/profile'
    put '/update_profile'
  end

  namespace :remote do
    get '/'=>:index
    namespace :auth do
      get '/register'
      post '/process_registration'
      get '/user_generation'
      post '/login'
      get :profile
      put :update_profile
    end
  end

  namespace :ajax do
    get '/cities'
  end

  namespace :quiz do
    root :to=>:index
    get '/instruction/:id' => :instruction, :as => :instruction
    get '/clear_result/:id' => :clear_result, :as => :clear_result
    get '/result/:id' => :result, :as => :result
    get '/run/:id' => :run, :as => :run
    get '/complete/:id' => :complete, :as => :complete
    match '/answer/:id/:question_id' => :answer, :as => :answer
    match '/view_report'
    match '/download_report'
  end

  get "/admin" => "admin#index", :as=>:admin
  get "/admin/login" => "admin#login", :as => :admin_login
  match '/admin/questions/:action/:id' => 'questions#index'
  match '/admin/questions/:action/:id.:format' => 'questions#index'

  namespace :admin do

# leave that *** after back end changes
    resources :users do
      member do
        get :profile
      end
    end
    resources :projects do
      member do
        get :codes
        get :settings
        get :quizes
        get :move_users
        post :apply_move_users
        get :notice_history
        get :send_all
        get :send_choosed
        get :send_uncompleted
        post :process_send
        get :excel_export
        get :reports
      end
      resources :notices do
        member do
          get :prev
          get :copy
          get :message_text
        end
        collection do
          get :preview
        end
      end
      resources :users do
        collection do
          post :import
          get :import_dialog
        end
        member do
          get :move_to_project
        end        
        resources :quizzes do
          member do
            get :reset
            get :show_answers
            get :show_statistics
            get :export_answers
            get :show_report
            get :export_report
          end
        end  
      end
      resources :quiz do        
      end
      collection do
        get :all_users
        get :users
      end
    end 

    resources :quizzes do
      resources :profile_charachteristic do        
      end
      resources :factors do
      end
      resources :reports do
      end
      member do
        get :settings
        get :statistics
        get :set_period
        get :excel_export
        get :excel_reports
      end
      resources :questions do        
        collection do
          post :save_weights
          post :save_buffering
          post :remove          
        end
        member do
          get :buffering
          get :move
        end
      end
    end

    resources :settings
    resources :pages

    namespace :users do
      match "/"=>:index
      match '/new'
      match '/edit/:id'=>:edit
      match '/update/:id'=>:update
      match '/delete/:id'=>:destroy
      match "/list"
    end

    namespace :quiz do
      match '/'=>:index
      match '/new'
      match '/delete/:id'=>:destroy
      match '/edit/:id'=>:edit
      match '/update/:id'=>:update
      match '/list'
      match '/import'
    end

    namespace :factor do
      match '/new/:id'=>:new
      match '/update/:id'=>:update
      match '/edit/:id'=>:edit
      match '/reorder'
      match '/questions/:id'=>:questions
      match '/delete/:id'=>:destroy
      match '/correlation/:id'=>:correlation
    end

    namespace :report do
      match '/new/:id'=>:new
      match '/update/:id'=>:update
      match '/edit/:id'=>:edit
      match '/delete/:id'=>:destroy
    end

    namespace :interpretation do
      match '/new'
      match '/update/:id'=>:update
      match '/delete/:id'=>:destroy
    end

    namespace :statistics do
      match '/' => :index
      match '/view_report'
      match '/answers'
      match '/user'
      match '/answers'
      match '/export'
      match '/clear_statistic'
    end

    namespace :notice do
      match '/edit'
      match '/create_or_update'
      match '/process_window'
      match '/delete/:id'=>:destroy
      match '/notice_window_content'
    end

    # namespace :pages do
    #   match '/' => :index
    #   match '/new'
    #   match '/edit/:id'=>:edit
    #   match '/update/:id'=>:update
    #   match '/delete/:id'=>:delete
    #   match '/reorder'
    # end

    namespace :properties do
      match '/' => :index
      match '/add' => :add, :as => :add
      match '/view'
      match '/edit/:id'=>:edit, :as => :edit
      match '/update/:id'=>:update, :as => :update
      match '/delete/:id' => :delete, :as => :delete
      match '/reorder/' => :reorder, :as => :reorder
      match '/cities/' => :cities, :as => :cities
      match '/reorder'
      match '/load' => :load, as: :load
      match '/ajax_list_properties/:id'=>:ajax_list_properties
    end

    # namespace :settings do
    #   match '/'=>:index
    #   match '/edit/:id'=>:edit
    #   match '/update/:id'=>:update
    # end

    namespace :userquiz do
      match '/list_json'
      match '/excel_export'
    end
  end

end

app/models/project.rb
# -*- encoding : utf-8 -*-
class Project < ActiveRecord::Base
  has_many :users, :order => 'surname', :dependent=>:destroy
  has_many :notices
  has_many :project_quizzes, :dependent=>:destroy
  has_many :quizzes, :through=>:project_quizzes
  has_many :user_quizzes, :through=>:users
  has_many :sended_notices

  validates :title, :presence => {:message => "Заголовок опроса не может быть пустым"}

  before_destroy{|project| false if project.default?}

  accepts_nested_attributes_for :project_quizzes, :allow_destroy => true

  def to_s
    title
  end

  def show_report_for(quiz)
    project_quizzes.find_by_quiz_id(quiz.id).try(:show_report)
  end

  def find_report(quiz)
  	project_quizzes.find_by_quiz_id(quiz.id).try(:report)
  end

  def user_quizzes_by(quiz)
    user_quizzes.where(:quiz_id=>quiz)
  end

  def statistic
    people_count = users.size
    quizzes.map{|quiz| {:title=>quiz.title, :all=>user_quizzes_by(quiz).size,
      :completed=>user_quizzes_by(quiz).completed.size, :people => people_count}}
  end

  def self.default
    find_by_default(true)
  end

end

# == Schema Information
#
# Table name: projects
#
#  id           :integer(4)      not null, primary key
#  title        :string(255)     not null
#  created_at   :datetime
#  updated_at   :datetime
#  allow_anonim :boolean(1)
#  default      :boolean(1)      default(FALSE)
#  style        :text
#

app/controllers/admin/projects_controller.rb
# -*- encoding : utf-8 -*-
#encoding: utf-8
class Admin::ProjectsController < AdminController

  respond_to :html, :js

  before_filter :init, :except => [ :index, :new, :create, :users, :all_users ]
  before_filter :get_projects, :only => [:index, :show, :users, :all_users, :notice_history]
  before_filter :set_section

  def index
    
  end

  def reports
    render :action => "leave", :layout => false
  end

  def show
    @users = @project.users
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def create
    @project = Project.create(params[:project])    
    @project.save if @project.valid?
    respond_with(@project)
  end

  def edit
    
  end

  def update
    # binding.pry
    @project.update_attributes(params[:project])
    respond_with(@project)
  end

  def destroy
    
  end

  def codes
    respond_with(@project)
  end

  def settings
    respond_with(@project)
  end

  def quizes
    respond_with(@project)
  end

  def all_users
    @active = 1
    @users = User.all
    @project = Project.default
    @all_users = true
    render "admin/users/index"
  end

  def users
    @active = 1
    render "admin/users/index"
  end
  
  def move_users
    @ids = params[:choosed]
    respond_with(@ids)    
  end

  def apply_move_users
    # binding.pry
    @new_proj = Project.find(params[:user][:project_id])
    @users = User.where(id: params[:user][:usr].map { |u| u[0].to_i })
    @users.update_all(project_id: @new_proj.id)
    respond_with(@users)
  end  

  def notice_history
    @project = Project.find(params[:id])
    @notices = @project.sended_notices.order("created_at desc")

    respond_with(@notices)
  end

  def send_all
    @users = @project.users
    @templates = @project.notices
    render :send_notice
  end

  def send_choosed
    # binding.pry
    @users = []
    @choosed = params[:choosed]
    @users = @choosed.collect { |c| User.find(c) } unless @choosed.nil?
    @templates = @project.notices
    render :send_notice
  end

  def send_uncompleted
    @users = @project.user_quizzes.uncompleted.collect { |uq| uq.user }
    @templates = @project.notices
    render :send_notice
  end

  def process_send
    # binding.pry
    @send = params[:send]
    template = Notice.find(@send[:template])
    user_ids = @send[:users]
    t = NoticeRenderer::Template.new
    t.template = template.content
    admin_email = Settings.get(:email)
    other_emails = @send[:admin_email].split(',')
    User.find(user_ids).each do |user|
      t.set_user(user)
      content = t.render()
      Notifier.invite(user, template.theme, content, template, @project).deliver
      Notifier.invite_copy_admin(admin_email, template.theme, content).deliver if @send[:send_copy] == "1"
      other_emails.each { |ae| Notifier.invite_copy_admin(ae, template.theme, content).deliver }
      # SendedNotice.create(user: user, project: @project, notice: template, text: "mail.body")
    end
    respond_with(@project)
  end

  def excel_export
    if params[:choosed].present?
      @users = @project.users.joins(:user_quizzes).where("user_quizzes.user_id in (?)", params[:choosed]).uniq
      @quizzes = @project.quizzes
    else
      @users = @project.users.joins(:user_quizzes).where("user_quizzes.complete = 1").uniq
      @quizzes = @project.quizzes.includes(:completed_users)
    end
    # binding.pry

    headers['Content-Type'] = "application/vnd.ms-excel"                                                                       
    headers['Content-Disposition'] = 'attachment; filename="users_'+ Time.now.strftime("%Y_%D_%H_%M") + '.xls"'                                                      
    headers['Cache-Control'] = ''
    
    render :layout =>false
  end

private 
  def init
    @project = Project.find(params[:id])
  end

  def get_projects
    @projects = Project.all
  end

  def set_section
    @section = "projects"
    @active = 2
  end

end

app/views/admin/projects/_errors.html.haml
- @project.errors.each do |attribute, message|
  %div= message

app/views/admin/projects/_main_part.html.haml
:javascript

  // UK Date Sorting
  jQuery.fn.dataTableExt.oSort['uk_date-asc'] = function(a, b) {
    var parsea = $('<div/>').append(a);
    var parseb = $('<div/>').append(b);
    
    var a = parsea.find('.quiz-date').text().trim();
    var b = parseb.find('.quiz-date').text().trim();
    
    var ukDatea = a.split('.');
    var ukDateb = b.split('.');

    var x = (ukDatea[2] + ukDatea[1] + ukDatea[0]) * 1;
    var y = (ukDateb[2] + ukDateb[1] + ukDateb[0]) * 1;

    return ((x < y) ? -1 : ((x > y) ? 1 : 0));
  };

  jQuery.fn.dataTableExt.oSort['uk_date-desc'] = function(a, b) {
    var parsea = $('<div/>').append(a);
    var parseb = $('<div/>').append(b);
    
    var a = parsea.find('.quiz-date').text().trim();
    var b = parseb.find('.quiz-date').text().trim();
    
    var ukDatea = a.split('.');
    var ukDateb = b.split('.');

    var x = (ukDatea[2] + ukDatea[1] + ukDatea[0]) * 1;
    var y = (ukDateb[2] + ukDateb[1] + ukDateb[0]) * 1;
    
    return ((x < y) ? 1 : ((x > y) ? -1 : 0));
  };


  $(document).ready(function(){
    var cols = [{ "bSortable": false },{ "bSortable": false },null,null,null,null];
    var count = #{@project.project_quizzes.count};
    for(i=0;i<count;i++){ cols.push({"sType": "uk_date"}); }
    var tableObj = $('#client-list').dataTable({
      "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
      "sPaginationType": "bootstrap",
      "aoColumns": cols,
      "aaSorting": [[2, "asc"]],
      "oLanguage": {
        "sProcessing":   "Подождите...",
        "sLengthMenu":   "Показать _MENU_ записей",
        "sZeroRecords":  "Записи отсутствуют.",
        "sInfo":         "Записи с _START_ до _END_ из _TOTAL_",
        "sInfoEmpty":    "Записи с 0 до 0 из 0",
        "sInfoFiltered": "(отфильтровано из _MAX_ записей)",
        "sInfoPostFix":  "",
        "sSearch":       "Поиск:",
        "sUrl":          "",
        "oPaginate": {
            "sFirst": "<<",
            "sPrevious": "Пред.",
            "sNext": "След.",
            "sLast": ">>"
        }
      }
    });

    tableObj.fnFilter("#{params[:user]}");
    $("#client-list").data('api', tableObj);
    $("#choose_all").click(function(){
      if($("#choose_all").is(":checked"))
        $("#client-list tr td").find(":checkbox").attr('checked', 'checked');
      else
        $("#client-list tr td").find(":checkbox").removeAttr('checked');
      Service.refreshMoveLink("#{move_users_admin_project_path(@project)}");
      Service.refreshSendLink("#{send_choosed_admin_project_path(@project)}");
      Service.refreshExportLink("#{excel_export_admin_project_path(@project, format: :xml)}");
    });
    $(".add-client").live('click', function(){
      $(this).button('loading');
    });   
    $(".edit-client").live('click', function(){      
    })
    $("input[name='choosed[]']").live('change', function(){
      Service.refreshMoveLink("#{move_users_admin_project_path(@project)}");
      Service.refreshSendLink("#{send_choosed_admin_project_path(@project)}");
      Service.refreshExportLink("#{excel_export_admin_project_path(@project, format: :xml)}")
    });
  });

.center-pane
  .tabbable
    %ul.nav.nav-tabs
      %li{class: params[:tab] != 'tab_clients' ? 'active' : ''}
        %a{ :href => "#tab_stat", "data-toggle" => "tab" }= "Статистика"
      %li{class: params[:tab] == 'tab_clients' ? 'active' : ''}
        %a{ :href => "#tab_clients", "data-toggle" => "tab" }= "Список кандидатов"
    .tab-content
      .tab-pane#tab_stat{class: params[:tab] != 'tab_clients' ? 'active' : ''}
        %table.table.table-striped.table-bordered.table-condensed
          %thead
            %tr
              %th Опросы
              %th Назначено
              %th Завершено
              %th Кол-во пользователей/кандидатов             
          %tbody
            - @project.statistic.each do |quiz|
              %tr
                %td= quiz[:title]
                %td= quiz[:all]
                %td= quiz[:completed]
                %td= quiz[:people]
      .tab-pane#tab_clients{class: params[:tab] == 'tab_clients' ? 'active' : ''}
        .dash-table
          .title            
          .buttons
            = link_to "Добавить кандидата", new_admin_project_user_path(@project, section: @section), class: "btn btn-primary add-client", remote: true, :"data-loading-text" => "Загрузка..."            
          %table.table.table-striped.table-bordered.table-condensed.tablesorter#client-list
            %thead
              %tr          
                %th.center= check_box_tag :choose_all 
                %th
                %th Фамилия
                %th Имя
                %th Отчество

                %th Email
                - @project.project_quizzes.each do |pq|
                  %th= pq.quiz.title
            %tbody
              - @users.each do |user|
                = render "user_item", user: user
          .t-footer
            

app/views/admin/projects/_main_part_notice_history.html.haml
:javascript
	$(document).ready(function(){
		var tableObj = $('#notice-list').dataTable({
			"sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
			"sPaginationType": "bootstrap",
			"oLanguage": {
				"sProcessing":   "Подождите...",
				"sLengthMenu":   "Показать _MENU_ записей",
				"sZeroRecords":  "Записи отсутствуют.",
				"sInfo":         "Записи с _START_ до _END_ из _TOTAL_",
				"sInfoEmpty":    "Записи с 0 до 0 из 0",
				"sInfoFiltered": "(из _MAX_)",
				"sInfoPostFix":  "",
				"sSearch":       "Поиск:",
				"sUrl":          "",
				"oPaginate": {
					"sFirst": "<<",
					"sPrevious": "<",
					"sNext": ">",
					"sLast": ">>"
				}
			}
		});
	});


.center-pane
	.dash-table
		.title
			= "Отправленные уведомления"   
			%span= "[#{@project.title}]"

	%table.table.table-striped.table-bordered.table-condensed.tablesorter#notice-list
		%thead
			%tr
				%th Дата
				%th Адресат ФИО
				%th Адресат E-mail
				%th Отправитель E-mail
				%th Шаблон

		%tbody
			- @notices.each do |item|
				%tr
					%td= item.created_at.strftime("%Y-%m-%d %H:%M")	
					%td= item.user.title
					%td= item.user.email
					%td= AppConfig.setting[:mail_robot]

					%td
						= link_to message_text_admin_project_notice_path(@project, item.notice, sended_notice_id: item.id), remote: true,  :"data-original-title" => "Просмотр", rel: :tooltip, id: "preview-link" do
							= item.notice.title	

app/views/admin/projects/_project_page.html.haml
= javascript_include_tag "jquery.zclip"
= javascript_include_tag 'redactor', 'redactor.ru'
= stylesheet_link_tag 'redactor'

#add-project-dialog-container
#notices-dialog-container
#users-dialog-container

.left-pane.projects  
  = link_to "Добавить проект", new_admin_project_path, class: "btn btn-success btn-large", remote: true
  .well
    %ul.nav.nav-list#projects-list
      %li.nav-header 
        = "Проекты"        
      - @projects.each do |project|
        %li{ :class => !@project.nil? && @project.id == project.id ? "active" : "" }
          = link_to admin_project_path(project) do
            %i.icon-list-alt
            = project.title
- unless @project.nil?
  = render "main_part"
  = render "right_part"

app/views/admin/projects/_project_quiz_fields.html.haml
.well 
  :javascript
    $(document).ready(function(){
      RadioButtons.refresh();

      $(".select-quiz").change(function(){
        getReports(this);
      });


    function getReports(element){
        var quiz_id = $(element).attr("value");
        var selected_id = $(element).attr("data-value");
        
        var el = $(element).parent().next().find('select');

        $.get('#{params[:id]}/reports?quiz_id='+quiz_id+'&value='+selected_id, function(data){
          $(el).empty();
          $(el).append(data);
        });
    };
    });

  .row
    .span3= f.select :quiz_id, Quiz.all.map {|q| [q.title, q.id]}, { :include_blank => false }, :class => "span3 select-quiz", :data => {:type => f.object.quiz_id, :value => f.object.report_id}
    .span3
      = f.select :report_id, {}, { :include_blank => false }, class: "select-report", data: f.object.report_id, id: "r#{f.object.quiz_id}"
  .row.mt5
    .span3= f.label :show_quiz_title, "Показывать название опросника?"
    .span2
      .btn-group#radio{ "data-toggle" => "buttons-radio", :"data-toggle-name" => "project[show_quiz_title]" }
        %button.btn{ :type => "button", :value => 1 }= "Да"
        %button.btn{ :type => "button", :value => 0 }= "Нет"
      = f.hidden_field :show_quiz_title
  .row.mt5
    .span3= f.label :show_report, "Отчет сразу?"
    .span2
      .btn-group#radio{ "data-toggle" => "buttons-radio", :"data-toggle-name" => "project[show_report]" }
        %button.btn{ :type => "button", :value => 1 }= "Да"
        %button.btn{ :type => "button", :value => 0 }= "Нет"
      = f.hidden_field :show_report
  .row.mt5
    .span3= f.label :escape_instruction, "Пропустить инструкцию?"
    .span2
      .btn-group#radio{ "data-toggle" => "buttons-radio", :"data-toggle-name" => "project[escape_instruction]" }
        %button.btn{ :type => "button", :value => 1 }= "Да"
        %button.btn{ :type => "button", :value => 0 }= "Нет"
      = f.hidden_field :escape_instruction
  .row.mt5
    .span2      
      = link_to_remove_fields "Удалить опрос", f, ".well", class: "btn btn-danger"

app/views/admin/projects/_right_part.html.haml
.right-pane.options
  .well
    %ul.nav.nav-list
      %li.nav-header Действия
      %li
        = link_to new_admin_project_user_path(@project), class: "add-client", remote: true, :"data-loading-text" => "Загрузка..." do        
          %i.icon-plus-sign
          Добавить кандидата
      - if @project.quizzes.count > 0
        %li
          = link_to excel_export_admin_project_path(@project, format: :xml), target: :balnk do
            %i.icon-th
            Экспорт всех в Excel
      %li
        = link_to excel_export_admin_project_path(@project, format: :xml), class: "export-choosen", target: :blank do
          %i.icon-check
          Экспорт выбранных в Excel
      %li.nav-header Проект
      %li
        = link_to settings_admin_project_path(@project), remote: true do
          %i.icon-wrench
          Параметры проекта
      %li#project-polls
        = link_to quizes_admin_project_path(@project), remote: true do
          %i.icon-list
          Опросы
      %li
        = link_to codes_admin_project_path(@project), remote: true do
          %i.icon-file
          Код для вставки
      %li.nav-header Легенда
      %li.legend    
        %button.btn{ disabled: :disabled }
          %i.icon-plus-sign
        Назначено
      %li.legend
        .btn.btn-warning
          %i.icon-time
        В процессе
      %li.legend
        .btn.btn-success
          %i.icon-ok-circle
        Выполнено
      %li.nav-header Опции      
      %li.move-clients
        = link_to move_users_admin_project_path(@project), class: "move-user-group", remote: true do
          %i.icon-move
          Переместить кандидатов
      %li.nav-header Уведомления
      %li.send-notification
        = link_to send_all_admin_project_path(@project), remote: true do
          %i.icon-envelope
          Отправить всем
      %li.send-notification
        = link_to send_choosed_admin_project_path(@project), remote: true, class: "send-to-choosed" do
          %i.icon-check
          Отправить выбранным
      %li.send-notification
        = link_to send_uncompleted_admin_project_path(@project), remote: true do
          %i.icon-envelope
          Отправить незавершимшим
      %li
        = link_to admin_project_notices_path(@project) do        
          %i.icon-cog
          Управление шаблонами
      %li.sended-notify
        = link_to notice_history_admin_project_path(@project) do
          %i.icon-cog
          Отправленные уведомления

app/views/admin/projects/apply_move_users.js.erb
<% unless @project.id == @new_proj.id %>
	<% @users.each do |u| %>
		Service.deleteUser(<%= u.id %>);
	<% end %>
	Service.showNoty('Пользователи успешо перемещены!');
<% end %>
$("#move-to-project").modal('hide');
$("#add-project-dialog-container").html("");

app/views/admin/projects/index.html.haml
= render 'project_page'

app/views/admin/projects/move_users.js.erb
<% if @ids.nil? %>
	Service.showNoty('Выберите одного или несколько кандидатов!', 'error');
<% else %>
	$("#add-project-dialog-container").html("<%= j(render "shared/projects/move_to_project_dialog") %>");
<% end %>

app/views/admin/projects/new.js.erb
$("#add-project-dialog-container").html("<%= j(render "shared/projects/add_dialog") %>");

app/views/admin/projects/notice_history.html.haml
#notices-dialog-container

.left-pane.projects  
  .well
    %ul.nav.nav-list#projects-list
      %li.nav-header 
        = "Проекты"        
      - @projects.each do |project|
        %li{ :class => !@project.nil? && @project.id == project.id ? "active" : "" }
          = link_to admin_project_notices_path(project) do
            %i.icon-list-alt
            = project.title
- unless @project.nil?
  = render "main_part_notice_history"
  = render "/admin/notices/right_part"

app/views/admin/projects/process_send.js.erb
$("#notice-history-dlg").modal('hide');
Service.showNoty('Уведомления успешно отправлены!');
$("#add-project-dialog-container").html('');

app/views/admin/projects/quizes.js.erb
$("#add-project-dialog-container").html("<%= j(render "shared/projects/quizes_dialog") %>");

app/views/admin/projects/send_notice.js.erb
<% if @users.count > 0 %>
	$("#add-project-dialog-container").html("<%= j(render "shared/projects/send_notice_dialog") %>");
<% else %>
	Service.showNoty('Нет выбранных пользователей!', 'warning');
<% end %>