config/routes.rb
# -*- encoding : utf-8 -*-
ProfCareer::Application.routes.draw do
  

  mount_sextant if Rails.env.development?

  #mount ImperaviRails::Engine => "/imperavi"

  mount Ckeditor::Engine => '/ckeditor'

  get "admin/login" => "admin#login"
  get "admin_users/sign_in" => "admin#login"
  get "admin/reset_password" => "admin#reset_password"
  post "admin/reset_password_save" => "admin#reset_password_save"
  
  devise_for :admin_users

  root :to => 'home#index'

  namespace :auth do
    post '/login'
    get '/logout'
    get '/register'
    post '/process_registration'
    get '/profile'
    put '/update_profile'
  end

  namespace :remote do
    get '/'=>:index
    namespace :auth do
      get '/register'
      post '/process_registration'
      get '/user_generation'
      post '/login'
      get :profile
      put :update_profile
    end
  end

  namespace :ajax do
    get '/cities'
  end

  namespace :quiz do
    root :to=>:index
    get '/instruction/:id' => :instruction, :as => :instruction
    get '/clear_result/:id' => :clear_result, :as => :clear_result
    get '/result/:id' => :result, :as => :result
    get '/run/:id' => :run, :as => :run
    get '/complete/:id' => :complete, :as => :complete
    match '/answer/:id/:question_id' => :answer, :as => :answer
    match '/view_report'
    match '/download_report'
  end

  get "/admin" => "admin#index", :as=>:admin
  get "/admin/login" => "admin#login", :as => :admin_login
  match '/admin/questions/:action/:id' => 'questions#index'
  match '/admin/questions/:action/:id.:format' => 'questions#index'

  namespace :admin do

# leave that *** after back end changes
    resources :users do
      member do
        get :profile
      end
    end
    resources :projects do
      member do
        get :codes
        get :settings
        get :quizes
        get :move_users
        post :apply_move_users
        get :notice_history
        get :send_all
        get :send_choosed
        get :send_uncompleted
        post :process_send
        get :excel_export
        get :reports
      end
      resources :notices do
        member do
          get :prev
          get :copy
          get :message_text
        end
        collection do
          get :preview
        end
      end
      resources :users do
        collection do
          post :import
          get :import_dialog
        end
        member do
          get :move_to_project
        end        
        resources :quizzes do
          member do
            get :reset
            get :show_answers
            get :show_statistics
            get :export_answers
            get :show_report
            get :export_report
          end
        end  
      end
      resources :quiz do        
      end
      collection do
        get :all_users
        get :users
      end
    end 

    resources :quizzes do
      resources :profile_charachteristic do        
      end
      resources :factors do
      end
      resources :reports do
      end
      member do
        get :settings
        get :statistics
        get :set_period
        get :excel_export
        get :excel_reports
      end
      resources :questions do        
        collection do
          post :save_weights
          post :save_buffering
          post :remove          
        end
        member do
          get :buffering
          get :move
        end
      end
    end

    resources :settings
    resources :pages

    namespace :users do
      match "/"=>:index
      match '/new'
      match '/edit/:id'=>:edit
      match '/update/:id'=>:update
      match '/delete/:id'=>:destroy
      match "/list"
    end

    namespace :quiz do
      match '/'=>:index
      match '/new'
      match '/delete/:id'=>:destroy
      match '/edit/:id'=>:edit
      match '/update/:id'=>:update
      match '/list'
      match '/import'
    end

    namespace :factor do
      match '/new/:id'=>:new
      match '/update/:id'=>:update
      match '/edit/:id'=>:edit
      match '/reorder'
      match '/questions/:id'=>:questions
      match '/delete/:id'=>:destroy
      match '/correlation/:id'=>:correlation
    end

    namespace :report do
      match '/new/:id'=>:new
      match '/update/:id'=>:update
      match '/edit/:id'=>:edit
      match '/delete/:id'=>:destroy
    end

    namespace :interpretation do
      match '/new'
      match '/update/:id'=>:update
      match '/delete/:id'=>:destroy
    end

    namespace :statistics do
      match '/' => :index
      match '/view_report'
      match '/answers'
      match '/user'
      match '/answers'
      match '/export'
      match '/clear_statistic'
    end

    namespace :notice do
      match '/edit'
      match '/create_or_update'
      match '/process_window'
      match '/delete/:id'=>:destroy
      match '/notice_window_content'
    end

    # namespace :pages do
    #   match '/' => :index
    #   match '/new'
    #   match '/edit/:id'=>:edit
    #   match '/update/:id'=>:update
    #   match '/delete/:id'=>:delete
    #   match '/reorder'
    # end

    namespace :properties do
      match '/' => :index
      match '/add' => :add, :as => :add
      match '/view'
      match '/edit/:id'=>:edit, :as => :edit
      match '/update/:id'=>:update, :as => :update
      match '/delete/:id' => :delete, :as => :delete
      match '/reorder/' => :reorder, :as => :reorder
      match '/cities/' => :cities, :as => :cities
      match '/reorder'
      match '/load' => :load, as: :load
      match '/ajax_list_properties/:id'=>:ajax_list_properties
    end

    # namespace :settings do
    #   match '/'=>:index
    #   match '/edit/:id'=>:edit
    #   match '/update/:id'=>:update
    # end

    namespace :userquiz do
      match '/list_json'
      match '/excel_export'
    end
  end

end

app/models/notice.rb
# -*- encoding : utf-8 -*-
class Notice < ActiveRecord::Base
  belongs_to :project
  
  # Этот аттрибут не сохраняется, нужен только для формы выбора шаблона
  attr_accessor :template
  
  def template
    return self.id
  end

end

# == Schema Information
#
# Table name: notices
#
#  id         :integer(4)      not null, primary key
#  owner_id   :integer(4)      default(0), not null
#  title      :string(255)     not null
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/admin/notice_controller.rb
# -*- encoding : utf-8 -*-
class Admin::NoticeController < AdminController

  def edit
  end

  def create_or_update
  end

  def process_window
    if(params['notice-scope'] == "save-or-create") then
      if (params[:id].blank?) then
        @notice = Notice.create(params[:notice])
      else
        @notice = Notice.find_by_id(params[:id])
        @notice.update_attributes(params[:notice])
      end
      render :update do |page|
        page.replace_html 'notice-message-content', :partial => 'editor'
      end
      return
    elsif params['notice-scope'] == "load-template" then
      if (params[:notice][:template].blank?) then
        @notice = Notice.new
      else
        @notice = Notice.find_by_id(params[:notice][:template])
      end
      render :update do |page|
        page.replace_html 'notice-message-content', :partial => 'editor'
      end
      return
    elsif params['notice-scope'] == "delivery" then
      user_ids = params[:users].try(:values) || []
      User.find(user_ids).each do |user|
        Notifier.invite(user,params[:notice][:title], params[:notice][:content]).deliver if user.email =~ /\A\w+@\w+\.\w+$/
        #Notifier.deliver_invite_copy(user,params[:notice][:title], params[:notice][:content])
      end
      render :update do |page|
        page << "noticeWindow.hide();"
      end
    end
  end

  def destroy
    @notice = Notice.find_by_id(params[:id])
    @notice.destroy
    @notice = nil
    render :update do |page|
        page.replace_html 'notice-message-content', :partial => 'editor'
    end
  end

  def notice_window_content
    if(params[:word].blank?) then
      @users = User.all(:order => 'surname, name')
    else
      @users = User.find(:all, :conditions => [ 'LOWER(name) LIKE ? OR LOWER(surname) LIKE ? OR LOWER(patronymic) LIKE ? OR LOWER(projects.title) LIKE ?',
        "#{params[:word]}%","#{params[:word]}%", "#{params[:word]}%", "#{params[:word]}%"
        ], :include => 'project', :order => 'surname, name')
    end
    project_id = (params[:project_id] || 0).to_i
    if project_id > 0 then
      @users = @users.select { |u| u.project_id == project_id }
    end
    @projects = Project.values_of(:title, :id)
    render :layout => false
  end
end

app/controllers/admin/notices_controller.rb
# -*- encoding : utf-8 -*-
class Admin::NoticesController < AdminController
	respond_to :html, :js

	before_filter :fill_variables
	before_filter :find_notice, only: [:edit, :update, :destroy, :copy, :prev]

	def index
		@projects = Project.all
		@notices = @project.notices
	end

	def new
		@is_project_section = params.has_key?(:section) ? params[:section] == "projects" : false
		@notice = Notice.new
		respond_with(@notice)
	end

	def create
		@is_project_section = params.has_key?(:section) ? params[:section] == "projects" : false
		@notice = Notice.new(params[:notice])
		@notice.project = @project
		@notice.save
		respond_with(@notice)
	end

	def prev
		respond_with(@notice)
	end

	def edit
		respond_with(@notice)
	end

	def update
		@notice.update_attributes(params[:notice])
		respond_with(@notice)
	end

	def destroy	
		@id = @notice.id
		@notice.destroy
		respond_with(@id)
	end

	def copy
		@notice = @notice.dup
		respond_with(@notice)
	end

	def preview
		unless params[:template_id].blank?
			@template = Notice.find(params[:template_id])
			t = NoticeRenderer::Template.new
    	t.template = @template.content
    	t.set_user(User.generate)
    	@content = t.render()
		end
		respond_with(@content)
  	end

  	def message_text
  		# binding.pry
  		@notice = SendedNotice.find(params[:sended_notice_id])
  		@content = @notice.text
  		respond_with(@content)
  	end

private

	def fill_variables
		@project = Project.find(params[:project_id])
	end

	def find_notice
		@notice = Notice.find(params[:id])
	end

end

app/views/admin/notices/_main_part.html.haml
.center-pane
  .dash-table
    .title
      = "Управление шаблонами"   
      %span= "[#{@project.title}]"
    .buttons      
      = link_to "Добавить шаблон", new_admin_project_notice_path(@project), class: "btn btn-primary", remote: true
    %table.table.table-striped.table-bordered.table-condensed.tablesorter#notice-list
      %thead
        %tr                              
          %th Название          
          %th Создан
          %th
      %tbody
        - @notices.each do |item|
          = render "notice_row", notice: item              
    .t-footer

app/views/admin/notices/_notice_row.html.haml
%tr{ id: "notice-item-#{notice.id}", :"notice-data" => notice.id }
  %td= notice.title
  %td= notice.created_at
  %td.center
    = link_to prev_admin_project_notice_path(@project, notice), remote: true, class: 'btn' do
      %i.icon-envelope
    .btn-group{:style => "display: inline-block; margin-bottom: 0px;"}
      = link_to '#', :class => "btn dropdown-toggle", "data-toggle" => "dropdown" do
        %i.icon-cog
        %span.caret
      %ul.dropdown-menu
        %li                     
          = link_to copy_admin_project_notice_path(@project, notice), remote: true do
            %i.icon-share
            = "Копировать..."
        %li                   
          = link_to edit_admin_project_notice_path(@project, notice), remote: true do
            %i.icon-edit
            = "Редактировать..."                  
        %li                   
          = link_to admin_project_notice_path(@project, notice), method: :delete, confirm: "Вы уверены?", remote: true do
            %i.icon-remove
            = "Удалить..."

app/views/admin/notices/_right_part.html.haml
.right-pane.options
	.well
		%ul.nav.nav-list
			%li.nav-header Действия
			%li
				= link_to admin_project_path(@project) do
					%i.icon-arrow-left
					Вернуться к проекту                  

app/views/admin/notices/copy.js.erb
$("#notices-dialog-container").html("<%= j(render "shared/notices/add_dialog") %>");

app/views/admin/notices/create.js.erb
$("#crud-notify-dlg").modal('hide');
<% if @is_project_section %>
  $("#add-project-dialog-container").css('visibility', '');
  Service.addOption("#send_template", <%= @notice.id %>, '<%= @notice.title %>')
<% else %>
  Service.addNotice("<%= j(render "admin/notices/notice_row", notice: @notice) %>", <%= @notice.id %>);
<% end %>
Service.showNoty("Шаблон успешно добавлен!");
$("#notices-dialog-container").html("");

app/views/admin/notices/destroy.js.erb
Service.deleteNotice(<%= @id %>);
Service.showNoty("Шаблон успешно удален!");

app/views/admin/notices/edit.js.erb
$("#notices-dialog-container").html("<%= j(render "shared/notices/edit_dialog") %>");

app/views/admin/notices/index.html.haml
= javascript_include_tag 'redactor', 'redactor.ru'
= stylesheet_link_tag 'redactor'

:javascript
  $(document).ready(function(){   
    var tableObj = $('#notice-list').dataTable({
      "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
      "sPaginationType": "bootstrap",
      "aoColumns":[
        null,
        null,
        { "bSortable": false }
      ],
      "oLanguage": {
        "sProcessing":   "Подождите...",
        "sLengthMenu":   "Показать _MENU_ записей",
        "sZeroRecords":  "Записи отсутствуют.",
        "sInfo":         "Записи с _START_ до _END_ из _TOTAL_ записей",
        "sInfoEmpty":    "Записи с 0 до 0 из 0 записей",
        "sInfoFiltered": "(отфильтровано из _MAX_ записей)",
        "sInfoPostFix":  "",
        "sSearch":       "Поиск:",
        "sUrl":          "",
        "oPaginate": {
            "sFirst": "Первая",
            "sPrevious": "Предыдущая",
            "sNext": "Следующая",
            "sLast": "Последняя"
        }
      }
    });
    $("#notice-list").data('api', tableObj);
  });

#notices-dialog-container

.left-pane.projects  
  .well
    %ul.nav.nav-list#projects-list
      %li.nav-header 
        = "Проекты"        
      - @projects.each do |project|
        %li{ :class => !@project.nil? && @project.id == project.id ? "active" : "" }
          = link_to admin_project_notices_path(project) do
            %i.icon-list-alt
            = project.title
- unless @project.nil?
  = render "main_part"
  = render "right_part"

app/views/admin/notices/message_text.js.erb
/*<% if @content.nil? %>
  Service.showNoty("Ошибка! Пустое сообщение", 'error', 1500);
<% else %>
  $.noty.close(window.previewAlert);
  window.previewAlert = Service.showNoty("<%= raw j(@content.gsub(/(\r\n|\n|\r)/,'')) %>", 'alert', 150000);
<% end %>*/

$("#notices-dialog-container").html("<%= j(render "shared/notices/message_text") %>");

app/views/admin/notices/new.js.erb
<% if @is_project_section %>
  $("#add-project-dialog-container").css('visibility', 'hidden');
  try{
    $.noty.close(window.previewAlert);
  }catch(e){}
<% end %>
$("#notices-dialog-container").html("<%= j(render "shared/notices/add_dialog") %>");

app/views/admin/notices/prev.js.erb
$("#notices-dialog-container").html("<%= j(render "shared/notices/prev") %>");	

app/views/admin/notices/preview.js.erb
<% if @content.nil? %>
  Service.showNoty("Выберите шаблон для просмотра!", 'error', 1500);
<% else %>
  $.noty.close(window.previewAlert);
  window.previewAlert = Service.showNoty("<strong>Просмотр шаблона: <%= @template.title %></strong><br/><b>Тема: </b><%= @template.theme %><br /><%= j(raw @content.gsub(/(\r\n|\n|\r)/,'')) %>", 'alert', 150000);
<% end %>

app/views/admin/notices/update.js.erb
Service.updateNotice("<%= j(render "admin/notices/notice_row", notice: @notice) %>", <%= @notice.id %>);
$("#crud-notify-dlg").modal('hide');
Service.showNoty("Шаблон успешно обновлен!");
$("#notices-dialog-container").html("");